Script started on 2015年03月10日 (週二) 17時32分40秒
]0;F74032031@2015cpp: ~F74032031@2015cpp:~$ git clone https://github.com/<your github account>/lab1.git[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[Config -l[Ki[C[C[C[C[C[C[C[2Pwhoami; pwd
F74032031
/home/F74032031
]0;F74032031@2015cpp: ~F74032031@2015cpp:~$ whoami; pwdgit clone https://github.com/<your github account>/lab1.git[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[Cwhoami; pwd[Kgit clone https://github.com/<your github account>/lab1.gityan-ang[K[K[K[K[K[K[K[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.git[1P/lab1.gity/lab1.gita/lab1.gitn/lab1.git-/lab1.gita/lab1.gitn/lab1.gitg/lab1.git
Cloning into 'lab1'...
warning: You appear to have cloned an empty repository.
]0;F74032031@2015cpp: ~F74032031@2015cpp:~$ exit

Script done on 2015年03月10日 (週二) 17時33分55秒
